name: Build

on: [ push, pull_request ]

jobs:

  dist:
    name: Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: |
        ./bootstrap.sh
        ./configure
    - name: Make source package
      run: make VERSION=${{ github.sha }} dist
    - name: Upload source package artifact
      uses: actions/upload-artifact@v3
      with:
        name: bzip3-${{ github.sha }}
        path: bzip3-${{ github.sha }}.tar.gz
    - name: Run distcheck
      run: make distcheck

  build:
    name: Build Matrix
    needs: [ dist ]
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest, macos-latest ]
        compiler: [ clang, gcc ]
        feature: [ with-pthread, without-pthread ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Download source package artifact
      uses: actions/download-artifact@v3
      with:
        name: bzip3-${{ github.sha }}
    - name: Extract source package
      run: tar --strip-components=1 -xf bzip3-${{ github.sha}}.tar.gz
    - name: Configure
      run: ./configure CC=${{ matrix.compiler }} --${{ matrix.feature }}
    - name: Make
      run: make
    - name: Check
      run: make roundtrip

  build-bsd:
    name: Build on FreeBSD
    needs: [ dist ]
    runs-on: macos-10.15
    steps:
    - name: Download source package artifact
      uses: actions/download-artifact@v3
      with:
        name: bzip3-${{ github.sha }}
    - name: Extract source package
      run: tar --strip-components=1 -xf bzip3-${{ github.sha}}.tar.gz
    - name: Build in FreeBSD VM
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        usesh: true
        run: |
          pkg install -y llvm gmake
          MAKE=gmake ./configure
          gmake
          gmake roundtrip

  build-archs:
    name: Build Matrix for non-x86 architectures
    needs: [ dist ]
    strategy:
      fail-fast: false
      matrix:
        compiler: [ clang, gcc ]
        feature: [ with-pthread, without-pthread ]
        arch: [ armv6, armv7, aarch64, s390x, ppc64le ]
    runs-on: ubuntu-latest
    steps:
    - name: Download source package artifact
      uses: actions/download-artifact@v3
      with:
        name: bzip3-${{ github.sha }}
    - name: Extract source package
      run: tar --strip-components=1 -xf bzip3-${{ github.sha}}.tar.gz
    - uses: uraimo/run-on-arch-action@v2
      name: Run in the container
      with:
        arch: ${{ matrix.arch }}
        distro: stretch
        shell: /bin/sh
        dockerRunArgs: |
          --volume "${PWD}:/bzip3"
        install: |
          apt update -q -y
          apt install -q -y clang gcc make
        run: |
          cd /bzip3
          ./configure CC=${{ matrix.compiler }} --${{ matrix.feature }} --disable-arch-native --disable-link-time-optimization
          make && make roundtrip
