name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15
    name: FreeBSD
    steps:
    - uses: actions/checkout@v2
    - name: FreeBSD
      id: freebsd
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        usesh: true
        prepare: pkg install -y llvm gmake
        run: |
          ./bootstrap.sh
          ./configure
          make
          make check
